development:
  sessions:
    default:
      database: question_bank_dev

      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: question_bank_test
      hosts:
        - localhost:27017